import localFont from "next/font/local";
import "./globals.css";

import { UserProvider } from "@auth0/nextjs-auth0/client";
import TanstackProvider from "./provider/tanstackProvider";

const offbit = localFont({
  src: "../../public/fonts/OffBit-DotBold.ttf",
  variable: "--font-offbit",
});

const vinson = localFont({
  src: [
    {
      path: "../../public/fonts/Vinson-Light.ttf",
      weight: "300",
    },
    {
      path: "../../public/fonts/Vinson-Regular.ttf",
      weight: "400",
    },
    {
      path: "../../public/fonts/Vinson-Bold.ttf",
      weight: "700",
    },
  ],
  variable: "--font-vinson",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${offbit.variable} ${vinson.variable} font-sans`}>
        <UserProvider>
          <TanstackProvider>{children}</TanstackProvider>
        </UserProvider>
      </body>
    </html>
  );
}
