import localFont from "next/font/local";
import "./globals.css";

import { UserProvider } from "@auth0/nextjs-auth0/client";

const OffBit = localFont({ src: "../../public/fonts/OffBit-DotBold.otf" });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <UserProvider>
        <body className={OffBit.className}>{children}</body>
      </UserProvider>
    </html>
  );
}
