import Image from "next/image";
import { Frame } from "@/components/ui/navbar/frame";

import CityParallax from "../components/ui/city_parallax";

export default function Home() {
  return (
    <div>
      {/*<Frame />*/}

      {/* Parallax background */}
      <div className="flex-col items-center align-center justify-center m-40 z-50">
        <div className="absolute inset-0 z-50">
          <CityParallax 
            sky_0={"/assets/citybg_day_0.jpg"} 
            sky_1={"/assets/citybg_day_1.jpg"} 
            sky_2={"/assets/citybg_day_2.jpg"}
            city_0={"/assets/citybg_blue_0.jpg"} 
            city_1={"/assets/citybg_blue_1.jpg"} 
            city_2={"/assets/citybg_blue_2.jpg"} 
            city_3={"/assets/citybg_blue_3.jpg"} 
          />
        </div>
      </div>

      {/* Text */}
      <div className="bg-bla text-wh p-52">
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus a interdum ligula, nec porttitor massa. Donec posuere pellentesque turpis. Nullam a sagittis nibh, eu aliquam turpis. Mauris vulputate at urna nec ullamcorper. Proin venenatis justo nisi, a rhoncus ex pellentesque sed. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Fusce consequat eu arcu id fermentum. Morbi a lectus eget turpis mattis lacinia sed vitae ligula. Nulla tempor, tortor vel congue dignissim, nunc enim mattis lectus, a fermentum massa tellus sit amet eros. Nulla id gravida arcu. In viverra et sem sit amet suscipit. Duis non auctor leo.

        Phasellus in euismod enim. Interdum et malesuada fames ac ante ipsum primis in faucibus. Duis aliquet fringilla nisl vel rhoncus. Aenean tempus laoreet nisi id dictum. Integer ultricies dictum sollicitudin. Phasellus semper congue felis vel congue. Pellentesque nisl odio, feugiat id tristique viverra, aliquet in lorem. Donec sit amet felis tristique, vehicula nisi vitae, sollicitudin dui. Suspendisse pulvinar lacus quis blandit efficitur. Suspendisse eget velit neque. Nulla facilisi. Nulla condimentum tortor in sem ornare, nec fringilla lorem eleifend. Etiam quis lacus id neque sollicitudin dapibus id cursus magna. In pharetra fermentum ipsum vel mattis. Morbi luctus nisl ac suscipit sodales.

        Morbi non neque id diam ullamcorper porttitor. Pellentesque eleifend, justo non sodales iaculis, enim nibh sodales ipsum, a convallis leo nisi eu ligula. Duis sed nunc molestie, dictum ante quis, porttitor felis. Curabitur elementum efficitur nulla a consequat. Mauris maximus facilisis sagittis. Nulla nulla nisl, gravida ac iaculis at, placerat eu ipsum. Praesent blandit purus sapien, id congue mauris varius vitae. In sed porttitor libero, eu feugiat tortor. Cras ac ex et dolor sagittis egestas.

        Nullam non convallis sapien, ac consectetur augue. Pellentesque fringilla porta dui, interdum imperdiet dui bibendum eu. Nulla mollis vestibulum est. Praesent volutpat, diam et efficitur suscipit, neque mi fringilla leo, vitae lacinia erat justo cursus enim. Mauris accumsan, ante id rhoncus tincidunt, dolor diam rhoncus justo, vel malesuada justo nulla ac ex. Suspendisse ultrices eleifend nisl, ut cursus dolor porta id. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Maecenas suscipit accumsan pulvinar.

        Donec iaculis imperdiet tortor ac ullamcorper. Nunc non vestibulum erat. Suspendisse ultrices ut mi vel lobortis. Nulla a aliquet magna. Duis volutpat, nisl rutrum ultrices egestas, odio augue pretium lectus, nec convallis odio massa at felis. Nulla vel cursus leo. Aliquam id nisl ut nisl semper viverra at quis sapien. Aliquam convallis faucibus est a commodo. Nulla sagittis viverra gravida. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. In eget eros hendrerit, maximus mi ac, congue quam. Vestibulum consectetur bibendum lorem id suscipit. Proin et odio dolor. Cras augue tortor, sollicitudin porttitor placerat vitae, auctor non ante. Sed ultricies tellus id purus blandit, ut tincidunt massa maximus. Curabitur molestie metus sit amet tortor pretium varius.

        Ut ac aliquet magna, eu gravida purus. Praesent consectetur convallis nunc, sit amet laoreet libero ullamcorper at. Duis lacinia pellentesque congue. Suspendisse pellentesque felis sem, nec vulputate dolor finibus nec. Duis maximus molestie nisl quis interdum. Phasellus eget feugiat felis. Cras convallis lectus at mi porta tincidunt. Donec non vulputate elit. Nunc eu sem a massa porttitor dictum. Praesent accumsan libero at vehicula tincidunt.

        Ut feugiat ullamcorper est quis fermentum. Maecenas placerat aliquet magna non interdum. Vivamus non sem tincidunt, bibendum nulla vitae, tristique ante. Aliquam quis ipsum a nibh porta bibendum ut vel leo. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam elementum diam lacus, sit amet lacinia nisi mollis id. Proin congue mauris magna, ac lacinia nunc pretium eget. Curabitur vestibulum mattis tortor, vitae tempor est eleifend sed. In hac habitasse platea dictumst. Nullam quis est non neque auctor sollicitudin. Etiam ut massa fermentum, feugiat mauris et, lobortis nisi. Donec aliquet lobortis est, id suscipit odio. Vivamus nec libero imperdiet, dictum nulla at, interdum felis.

        Praesent rhoncus nunc vel sem interdum, in pharetra est mollis. Integer mattis eleifend tellus, a pretium mauris finibus at. In ultrices lacus nisi, non venenatis diam dignissim eget. Nulla facilisi. Suspendisse sed ultricies mauris, a consequat lorem. Morbi dictum urna magna, at aliquet sapien convallis eu. Curabitur non ultrices diam. Maecenas volutpat quis enim id aliquam. Donec a eros a velit consectetur placerat. Sed quis consequat urna. Quisque luctus tincidunt dui. Integer ullamcorper augue in facilisis maximus. Sed ut ullamcorper risus. Proin a erat id justo tincidunt faucibus sit amet non nunc. Nam consequat rhoncus elementum.

        Suspendisse potenti. In volutpat leo vel lacus accumsan, in facilisis augue sagittis. Phasellus sed felis est. Curabitur et ipsum eget dui ultricies gravida a rhoncus massa. Aenean viverra purus nibh, quis sagittis nulla tincidunt ut. Nunc nec blandit ipsum. Ut molestie nec eros a ultrices. Pellentesque sed tellus rhoncus, tincidunt nunc in, vehicula mi. Duis vehicula mauris et magna consectetur posuere. In in ligula at eros tincidunt maximus. Integer euismod ligula nec mi congue, scelerisque interdum lorem euismod. Donec dictum tempus tellus, vel aliquet eros porttitor in.

        Maecenas sit amet sapien pulvinar, cursus felis rhoncus, suscipit mi. Nam interdum consectetur lorem sed egestas. Praesent pharetra aliquet ipsum, vestibulum accumsan metus maximus in. Aenean mollis enim eget eros iaculis, et volutpat est gravida. Duis in ornare lacus, id bibendum nisl. Praesent facilisis sit amet tellus aliquet fringilla. Pellentesque sagittis, sem nec volutpat tristique, eros dolor condimentum arcu, ut consequat massa ipsum in magna. Maecenas malesuada orci nunc, ultrices mollis dolor blandit in. Sed tincidunt, sapien at tempus iaculis, lectus dolor imperdiet diam, vel bibendum felis magna in tellus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.

        Nam molestie, ipsum at aliquet auctor, magna neque finibus leo, quis egestas mauris ligula in nunc. Nullam iaculis luctus hendrerit. Cras metus dolor, scelerisque ac ligula vel, condimentum mollis metus. Donec tristique nibh non felis fermentum hendrerit. Maecenas a odio euismod, pretium tortor vitae, vehicula sem. Quisque a tortor consectetur ex rutrum efficitur sed nec justo. Suspendisse sit amet ultricies enim. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. In hac habitasse platea dictumst. Cras accumsan eros sit amet dui aliquet, id rhoncus ex euismod. Nullam id consectetur enim, vel porta arcu. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Morbi id odio semper tortor commodo venenatis et eget velit.

        Donec fermentum finibus eros vel mollis. Quisque sit amet lorem vel elit maximus aliquam maximus placerat dui. Vivamus at volutpat nunc. Nam quis libero ut velit laoreet facilisis quis eu ex. Proin quis pulvinar nisl, at convallis neque. Donec rutrum euismod sapien, ut aliquam augue eleifend sed. Maecenas enim ante, efficitur vel turpis ut, malesuada lobortis nibh. Ut ultricies sodales nunc at condimentum. Nunc vulputate quam ac arcu porta, eget elementum dui finibus. Duis eu sollicitudin erat, in egestas magna. Praesent hendrerit nisi quis lacus pharetra vulputate. Cras aliquet viverra nisl, quis pellentesque metus eleifend id. Phasellus magna tortor, pharetra a nibh quis, rutrum posuere mauris. Donec vehicula ullamcorper lorem eu accumsan.

        Proin tempor risus diam, ac tincidunt erat suscipit sed. Nulla facilisis tristique eros, non tempor dolor. Fusce vel magna lorem. Integer ut ipsum in enim ultricies dapibus. Fusce ut nibh at tellus feugiat ornare at suscipit lectus. Fusce magna arcu, tempus in vestibulum quis, sodales eu metus. In ut lorem vel leo varius mattis. Quisque pellentesque porttitor magna, non scelerisque lectus dapibus finibus. Nam gravida lacus risus, sit amet gravida lectus scelerisque eu. Donec euismod interdum sapien, eleifend vestibulum augue elementum a. Praesent ante mi, venenatis consequat sodales id, rutrum nec neque. Duis maximus, nulla in malesuada eleifend, risus lorem viverra felis, vitae feugiat purus ex a mauris. Sed egestas ultrices mollis. Fusce a libero dapibus, vehicula nisl vitae, luctus justo. Nulla odio dolor, venenatis a tincidunt nec, congue vel nibh. Ut mattis ut dui et faucibus.

        Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Morbi at venenatis sem, eu suscipit turpis. Phasellus facilisis pulvinar lacinia. Ut faucibus sem vel est viverra, at feugiat enim volutpat. Proin non placerat felis, ac lacinia mauris. Duis lobortis dolor ornare lacus consectetur, a finibus dui elementum. Quisque accumsan mi lorem, a condimentum tortor porttitor interdum. Ut eu nisi odio. Sed sed lectus dolor. Aliquam gravida leo ante, sit amet imperdiet lacus volutpat et. Aliquam aliquam ante lectus, sed porttitor libero interdum nec. Fusce congue mattis felis vel iaculis. Pellentesque varius dolor quis eleifend hendrerit.

        Pellentesque purus magna, pharetra sed pulvinar nec, tempor eu massa. Integer erat ante, tincidunt ut convallis sit amet, lobortis quis lorem. Suspendisse non sem pellentesque, condimentum tellus ac, faucibus neque. Fusce venenatis, nibh vel venenatis rutrum, elit velit tincidunt ante, dapibus fermentum felis arcu ut dui. Cras vestibulum augue tellus, at euismod risus semper nec. Etiam in viverra enim. Nulla facilisi. Aenean a sollicitudin elit. Donec nec hendrerit lorem, in tristique diam. Sed sit amet urna id lorem rhoncus blandit aliquet in ante. Fusce eros erat, accumsan a auctor at, facilisis nec metus.

        Etiam rutrum elit quis est sagittis, at imperdiet nibh consequat. Suspendisse luctus elit et hendrerit aliquam. Donec quis laoreet elit. Nulla et dui malesuada, suscipit ex ac, rhoncus turpis. Fusce mattis, ex eget ullamcorper fermentum, ligula ex posuere nisl, et efficitur ante massa a libero. Maecenas ipsum sem, cursus id arcu eget, scelerisque rhoncus erat. Interdum et malesuada fames ac ante ipsum primis in faucibus. Integer ut mauris scelerisque, volutpat lacus vitae, sollicitudin arcu. Fusce faucibus mollis efficitur. Phasellus posuere euismod auctor. Nunc congue tellus risus, vitae euismod felis laoreet quis. Duis sit amet mi in mi vehicula commodo sit amet quis nibh.

        Pellentesque augue purus, varius vel viverra ac, ultrices a nulla. Aliquam et malesuada odio. Suspendisse porta iaculis quam, a tempor metus pellentesque non. Nullam hendrerit porttitor augue at ornare. Nullam iaculis tortor a sem ullamcorper, id tincidunt velit interdum. Donec ultrices interdum libero, ut accumsan ligula semper ac. Aliquam nec pellentesque dui. Aliquam maximus fringilla nisi, eu tempus quam finibus porta. Aenean volutpat mauris at orci molestie, vel maximus dolor viverra. Integer tempus pellentesque elementum. Vivamus in erat elementum, vulputate quam et, dapibus justo. Integer scelerisque ipsum vitae diam porttitor euismod. Duis sit amet eros nec est vestibulum laoreet quis posuere nisl. Donec pretium maximus laoreet. Mauris scelerisque lacinia augue, eu finibus arcu iaculis posuere.

        Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Nulla ac pretium risus, ut sagittis nisl. Integer quis congue nisl, a bibendum neque. Phasellus sollicitudin augue in turpis fermentum lacinia. In fermentum, leo id vestibulum vulputate, felis ex tincidunt nisl, vel interdum eros tortor sed ex. Pellentesque luctus condimentum mollis. Maecenas sit amet diam aliquam, pharetra risus a, viverra ligula. Morbi lobortis fermentum interdum. In posuere, turpis eu dignissim gravida, sapien mauris tempor mi, et consectetur odio orci non nibh.

        Ut sodales et justo sit amet feugiat. Integer non risus ut felis auctor mollis. Morbi eu diam sed ante fermentum pharetra. Maecenas maximus lacus neque, eu scelerisque justo tristique eget. Morbi eget felis rutrum turpis accumsan ultrices molestie et libero. In varius imperdiet mi, eget finibus mi vestibulum vitae. Pellentesque maximus erat lacus, et molestie nulla euismod sed. Suspendisse potenti. Pellentesque aliquam dolor lacus, id luctus leo luctus sed. Aliquam quis hendrerit turpis, cursus auctor libero. Sed suscipit elit nec elit venenatis volutpat. Aenean pretium ipsum at lacus euismod, ac auctor magna posuere. Nullam sit amet est sed justo efficitur vehicula. Sed accumsan ipsum a gravida euismod.

        Etiam vel dui id nibh interdum hendrerit. Mauris posuere tempus pulvinar. Aliquam laoreet vulputate libero, in lacinia dui tempus sit amet. Pellentesque finibus dolor pretium risus sollicitudin, ac vulputate arcu sagittis. In sagittis consectetur sem nec pharetra. Duis pellentesque est id hendrerit sollicitudin. Donec tincidunt ullamcorper elit, ut facilisis nisl tempor non. Fusce sodales eu metus sed pharetra. Integer nunc nunc, cursus a metus eu, volutpat ultricies eros. Etiam dapibus iaculis sagittis. Quisque et quam condimentum, rutrum justo ac, varius urna. Vestibulum iaculis lectus et ipsum elementum consequat. Duis tempor neque ac arcu finibus commodo. Donec id pellentesque lorem. Donec eget nisl a felis lobortis ultricies sit amet ac justo.

      </div>
    </div>
  );
}
